# Generated by Django 4.0.4 on 2022-06-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_name', models.CharField(max_length=100)),
                ('serie_clasificacion', models.CharField(max_length=50)),
                ('serie_num_capitulos', models.SmallIntegerField()),
                ('serie_num_temporadas', models.SmallIntegerField()),
                ('serie_poster', models.ImageField(upload_to='')),
                ('serie_ranking', models.BigIntegerField()),
                ('serie_cast', models.TextField()),
                ('serie_created_at', models.DateField()),
                ('serie_property_of', models.CharField(max_length=100)),
                ('serie_trailer', models.BooleanField()),
            ],
        ),
    ]
