# Generated by Django 4.0.4 on 2022-06-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='serie_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='serie_num_capitulos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='series',
            name='serie_num_temporadas',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='series',
            name='serie_poster',
            field=models.ImageField(default='null', upload_to=''),
        ),
        migrations.AlterField(
            model_name='series',
            name='serie_ranking',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='series',
            name='serie_trailer',
            field=models.TextField(),
        ),
    ]
